# Generated by Django 5.2.17 on 2026-08-26 13:54

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_waitlistentry_user_terms_accepted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='evidence',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/app/private_media')), upload_to='verification/%Y/%m/'),
        ),
    ]
