# Generated by Django 5.2.17 on 2026-08-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_verificationrequest_evidence'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='brandprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('cvr', ''), _negated=True), fields=('cvr',), name='unique_cvr_when_set'),
        ),
    ]
