# Generated by Django 5.2.17 on 2026-08-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_brandprofile_unique_cvr_when_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_prompt_dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
