# Generated by Django 5.2.17 on 2026-09-03 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_password_prompt_dismissed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitecode',
            name='used_by',
        ),
        migrations.DeleteModel(
            name='WaitlistEntry',
        ),
        migrations.DeleteModel(
            name='InviteCode',
        ),
    ]
