# Generated by Django 5.2.17 on 2026-09-03 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_invitecode_waitlistentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dawa_id', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('municipality_code', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['name', 'municipality'],
            },
        ),
        # Free-text city replaced by a FK; existing values are dropped on purpose.
        migrations.RemoveField(model_name='brandprofile', name='city'),
        migrations.AddField(
            model_name='brandprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.city'),
        ),
        # Free-text city replaced by a FK; existing values are dropped on purpose.
        migrations.RemoveField(model_name='creatorprofile', name='city'),
        migrations.AddField(
            model_name='creatorprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.city'),
        ),
    ]
