# Generated by Django 5.2.17 on 2026-09-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('snapchat', 'Snapchat'), ('linkedin', 'LinkedIn'), ('x', 'X'), ('threads', 'Threads'), ('twitch', 'Twitch'), ('pinterest', 'Pinterest')], max_length=20),
        ),
    ]
