# Generated by Django 5.2.17 on 2026-09-03 09:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_more_social_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='bio_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None),
        ),
    ]
