# Generated by Django 5.2.17 on 2026-09-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_portfolioitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('snapchat', 'Snapchat'), ('linkedin', 'LinkedIn')], max_length=20),
        ),
    ]
