# Generated by Django 5.2.17 on 2026-09-03 10:20

import accounts.crypto
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_nichetag_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', accounts.crypto.EncryptedTextField()),
                ('refresh_token', accounts.crypto.EncryptedTextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes_granted', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('followers', models.BigIntegerField(blank=True, null=True)),
                ('posts', models.BigIntegerField(blank=True, null=True)),
                ('engagement_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='verified',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='sync_failures',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='verification_method',
            field=models.CharField(choices=[('none', 'Not verified'), ('manual', 'Manual (screenshot reviewed by staff)'), ('oauth', 'OAuth')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests', to='accounts.sociallink'),
        ),
        migrations.AddConstraint(
            model_name='sociallink',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('platform', 'external_id'), name='unique_external_id_per_platform'),
        ),
        migrations.AddField(
            model_name='channelcredential',
            name='channel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='accounts.sociallink'),
        ),
        migrations.AddField(
            model_name='channelmetricsnapshot',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='accounts.sociallink'),
        ),
        migrations.AddConstraint(
            model_name='channelmetricsnapshot',
            constraint=models.UniqueConstraint(fields=('channel', 'captured_at'), name='one_snapshot_per_instant'),
        ),
    ]
