/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BioEditor: typeof import('./src/components/BioEditor.vue')['default']
    ChannelEditor: typeof import('./src/components/ChannelEditor.vue')['default']
    CityPicker: typeof import('./src/components/CityPicker.vue')['default']
    FieldHint: typeof import('./src/components/FieldHint.vue')['default']
    HashtagText: typeof import('./src/components/HashtagText.vue')['default']
    InstallApp: typeof import('./src/components/InstallApp.vue')['default']
    KvaekkerGame: typeof import('./src/components/KvaekkerGame.vue')['default']
    NichePicker: typeof import('./src/components/NichePicker.vue')['default']
    ReportButton: typeof import('./src/components/ReportButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAlert: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UEditor: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Editor.vue')['default']
    UEditorMentionMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/EditorMentionMenu.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UTextarea: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
    WelcomePasswordPrompt: typeof import('./src/components/WelcomePasswordPrompt.vue')['default']
  }
}
