# Generated by Django 5.2.17 on 2026-08-26 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mollie_payment_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('amount_ore', models.PositiveIntegerField()),
                ('currency', models.CharField(default='DKK', max_length=3)),
                ('status', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='open', max_length=10)),
                ('checkout_url', models.URLField(blank=True)),
                ('provider_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='campaigns.campaign')),
            ],
        ),
    ]
