# Generated by Django 5.2.17 on 2026-08-26 20:34

import django.core.files.storage
import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('seller_name', models.CharField(max_length=200)),
                ('seller_cvr', models.CharField(blank=True, max_length=8)),
                ('seller_address', models.CharField(blank=True, max_length=300)),
                ('seller_email', models.EmailField(blank=True, max_length=254)),
                ('buyer_company', models.CharField(max_length=200)),
                ('buyer_cvr', models.CharField(blank=True, max_length=8)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=300)),
                ('net_ore', models.PositiveIntegerField()),
                ('vat_ore', models.PositiveIntegerField()),
                ('gross_ore', models.PositiveIntegerField()),
                ('pdf', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/app/private_media')), upload_to='invoices/%Y/')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='billing.payment')),
            ],
        ),
    ]
