# Generated by Django 5.2.17 on 2026-08-26 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('standard', 'Standard'), ('reach', 'Reach')], max_length=10)),
                ('briefs_total', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='accounts.brandprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('declined', 'Declined'), ('negotiating', 'Negotiating'), ('accepted', 'Accepted'), ('closed', 'Closed')], default='sent', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefs', to='accounts.creatorprofile')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefs', to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_amount_ore', models.PositiveIntegerField()),
                ('agreed_terms', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand_completed_at', models.DateTimeField(blank=True, null=True)),
                ('creator_completed_at', models.DateTimeField(blank=True, null=True)),
                ('brief', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='campaigns.brief')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField()),
                ('author', models.CharField(choices=[('creator', 'Creator'), ('brand', 'Brand')], max_length=10)),
                ('amount_ore', models.PositiveIntegerField(help_text='Creator compensation in øre (off-platform in MVP)')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('superseded', 'Superseded'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='campaigns.brief')),
            ],
            options={
                'ordering': ['round'],
            },
        ),
        migrations.AddConstraint(
            model_name='brief',
            constraint=models.UniqueConstraint(fields=('campaign', 'creator'), name='one_brief_per_creator_per_campaign'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(fields=('brief', 'round'), name='one_proposal_per_round'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.CheckConstraint(condition=models.Q(('round__gte', 1), ('round__lte', 3)), name='proposal_round_bounds'),
        ),
    ]
