# Generated by Django 5.2.17 on 2026-09-03 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='proposal',
            name='proposal_round_bounds',
        ),
    ]
