# Generated by Django 5.2.17 on 2026-08-26 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlists', to='accounts.brandprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ShortlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlist_entries', to='accounts.creatorprofile')),
                ('shortlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='discovery.shortlist')),
            ],
        ),
        migrations.CreateModel(
            name='SwipeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('like', 'Like'), ('pass', 'Pass')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='accounts.brandprofile')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_received', to='accounts.creatorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to='accounts.brandprofile')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to='accounts.creatorprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['brand', 'creator', '-created_at'], name='discovery_p_brand_i_eaa50f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='shortlist',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='unique_shortlist_name_per_brand'),
        ),
        migrations.AddConstraint(
            model_name='shortlistentry',
            constraint=models.UniqueConstraint(fields=('shortlist', 'creator'), name='unique_creator_per_shortlist'),
        ),
        migrations.AddIndex(
            model_name='swipeevent',
            index=models.Index(fields=['brand', 'creator', '-created_at'], name='discovery_s_brand_i_d5943f_idx'),
        ),
    ]
